name: Build Android App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'  # Use a stable version
          bundler-cache: true

        # Install fastlane
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install
          gem install fastlane
          
      - name: Decode Keystore
        run: |
          mkdir -p app
          echo ${{ secrets.KEYSTORE_FILE_BASE64 }} | base64 --decode > app/chatterAndroidKey.jks
      
      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
