name: Build Android App
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          
      - name: Install Fastlane
        run: |
          gem install bundler
          gem install fastlane

      - name: Build Android App with Fastlane
        working-directory: android
        run: |
          bundle exec fastlane android build
          
      - name: Decode Keystore
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: |
          mkdir -p android/app
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > android/app/release.jks
      
      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: android
          keystore-content: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
