name: Build Android App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_FILE_BASE64 }} | base64 --decode > app/release.jks
      
      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
