name: Build Android App
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        run: |
          echo ${{ secrets.LLQQ_ANDROIDCHATTER_KEYSTORE_FILE_BASE64 }} | base64 --decode > app/release.jks
      
      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.LLQQ_ANDROIDCHATTER_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.LLQQ_ANDROIDCHATTER_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.LLQQ_ANDROIDCHATTER_KEY_PASSWORD }}
